services:
 conjuring:
  container_name: conjuring
  image: conjuring/conjuring:latest
  build:
   context: .
   target: conjuring
   cache_from:
   - conjuring/conjuring:base
   - conjuring/conjuring:core
   - conjuring/conjuring:latest
   args:
    GROUP_ID: ${GROUPS:-1000}
  depends_on:
  - core
  hostname: conjuring
  #network_mode: host
  #deploy: {resources: {reservations: {devices: [{driver: nvidia, count: all, capabilities: [gpu]}]}}}
  #shm_size: 4gb
  restart: unless-stopped
  ports:
  - "8989:8000"
  volumes:
  - ./custom/shared:/shared:ro
  - ./custom/home_default:/opt/home_default:ro
  - ./custom/home:/home
 core:
  image: conjuring/conjuring:core
  build:
   context: .
   target: core
   cache_from:
   - conjuring/conjuring:base
   - conjuring/conjuring:core
  depends_on:
  - base
  command: ["/bin/bash", "-c", "exit 0"]
 base:
  image: conjuring/conjuring:base
  build:
   context: .
   dockerfile: custom/base.Dockerfile
   target: base
   cache_from:
   - conjuring/conjuring:base
  command: ["/bin/bash", "-c", "exit 0"]
