version: '3.4'
services:
 conjuring:
  container_name: conjuring
  image: casperdcl/conjuring:latest
  build:
   context: .
   target: conjuring
   cache_from:
    - casperdcl/conjuring:base
    - casperdcl/conjuring:core
    - casperdcl/conjuring:latest
   args:
    GROUP_ID: ${GROUPS:-1000}
  hostname: conjuring
  # cap_add:
  #  - NET_ADMIN
  # network_mode: "host"  # host only works on linux: https://docs.docker.com/network/host/
  #runtime: nvidia
  restart: unless-stopped
  shm_size: 4gb
  ports:
   - "8989:8000"
  volumes:
  #- home:/home
  - ./home_default:/opt/home_default
 core:
  image: casperdcl/conjuring:core
  build:
   context: .
   target: core
   cache_from:
    - casperdcl/conjuring:base
    - casperdcl/conjuring:core
 base:
  image: casperdcl/conjuring:base
  build:
   context: .
   dockerfile: base.Dockerfile
   target: base
   cache_from:
    - casperdcl/conjuring:base
