version: '3.4'
services:
 conjuring:
  container_name: conjuring
  image: casperdcl/conjuring:latest
  build:
   context: .
   target: conjuring
   cache_from:
   - casperdcl/conjuring:base
   - casperdcl/conjuring:core
   - casperdcl/conjuring:latest
   args:
    GROUP_ID: ${GROUPS:-1000}
  depends_on:
  - core
  hostname: conjuring
  #network_mode: host
  #runtime: nvidia
  #shm_size: 4gb
  restart: unless-stopped
  ports:
  - "8989:8000"
  volumes:
  - ./custom/shared:/shared:ro
  - ./custom/home_default:/opt/home_default
  - ./custom/home:/home
 core:
  image: casperdcl/conjuring:core
  build:
   context: .
   target: core
   cache_from:
   - casperdcl/conjuring:base
   - casperdcl/conjuring:core
  depends_on:
  - base
  command: ["/bin/bash", "-c", "exit 0"]
 base:
  image: casperdcl/conjuring:base
  build:
   context: .
   dockerfile: custom/base.Dockerfile
   target: base
   cache_from:
   - casperdcl/conjuring:base
  command: ["/bin/bash", "-c", "exit 0"]
